server:
  servlet:
    context-path: /javaitembank


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.58:3306/javaitembank
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    servlet:
      content-type: text/html
    mode: HTML5
    encoding: utf-8
    cache: false




mybatis:
  type-aliases-package: com.yu.domain





